name = "sky-ai-api"
main = "workers/api/src/worker.ts"
compatibility_date = "2026-03-05"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ENVIRONMENT = "dev"
AIG_ACCOUNT_ID = "119641edf4fbeb5ac613d6b7db85f691"
AIG_GATEWAY_ID = "sky-ai"
OPENAI_MODEL = "gpt-4o-mini"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
ACCESS_AUTH_ENABLED = true
ALLOW_API_KEY_BYPASS = true
WORKERS_AI_EMBEDDING_MODEL = "@cf/baai/bge-base-en-v1.5"
WORKERS_AI_CHAT_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
VECTOR_DIMENSIONS = "1536"
BETTER_AUTH_URL = "https://sky-ai-api.ahmad22selim.workers.dev"

[[d1_databases]]
binding = "SKY_DB"
database_name = "sky-ai-dev"
database_id = "cd67c1c8-66db-43d2-9b43-4e3ec6398d04"
migrations_dir = "db/migrations"

[[vectorize]]
binding = "SKY_VECTORIZE"
index_name = "sky-ai-memory-dev"

[ai]
binding = "AI"

[env.prod.vars]
ENVIRONMENT = "prod"
AIG_ACCOUNT_ID = "119641edf4fbeb5ac613d6b7db85f691"
AIG_GATEWAY_ID = "sky-ai"
OPENAI_MODEL = "gpt-4o-mini"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
ACCESS_AUTH_ENABLED = true
ALLOW_API_KEY_BYPASS = false
WORKERS_AI_EMBEDDING_MODEL = "@cf/baai/bge-base-en-v1.5"
WORKERS_AI_CHAT_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
VECTOR_DIMENSIONS = "1536"
BETTER_AUTH_URL = "https://sky-ai-api.ahmad22selim.workers.dev"

[[env.prod.d1_databases]]
binding = "SKY_DB"
database_name = "sky-ai-prod"
database_id = "e0dc4ec1-26d5-46db-819d-a416bb76c7ec"
migrations_dir = "db/migrations"

[[env.prod.vectorize]]
binding = "SKY_VECTORIZE"
index_name = "sky-ai-memory-prod"

[env.prod.ai]
binding = "AI"
